spring:
  config:
    import: "classpath:META-INF/build-info.properties"


greet.message: "Hey Hi Welcome to Spring Cloud Config Server World... :) - from main branch"

server.port: 1122
  

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30
  client:
    lease.duration: 30


info:
    name: "Spring Cloud Discovery Service Registry is Running on : ${build.version}"

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /manage
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true
