spring:
  application:
    name: test-service
  config:
    import: "classpath:META-INF/build-info.properties"

server.port: 1122

greet.message: "Hey hi Welcome to Spring Cloud Config Server World... :) - integration branch"

info:
    name: "Spring Cloud Discovery Service Registry is Running on : ${build.version}"

management:
  endpoints:
    web:
      exposure:
        include: 'info,beans,health'
      base-path: /manage
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: false
    build:
      enabled: false
